sudo: required

language: node_js

services:
  - docker

env:
  global:
    - COMMIT=${TRAVIS_COMMIT::7}

install:
  - npm install --silent

script:
  - npm run build:ssr --silent

after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  - export WEB_CLIENT=egorrepnikov/artaeum-web-client
  - docker build -t $WEB_CLIENT:$COMMIT
  - docker tag $WEB_CLIENT:$COMMIT $WEB_CLIENT:$TAG
  - docker push $WEB_CLIENT
